package org.seleniumdemo.utils;

import java.util.Arrays;
import java.util.List;

public class ListaTitulos {
    public static List<String> listaTitulos = Arrays.asList(
            "300",
            "1408",
            "1922",
            "[•REC] 4: Apocalipsis",
            "¡Qué dilema!",
            "12 monos",
            "13 fantasmas",
            "13 pecados",
            "13 Tzameti",
            "18 comidas",
            "20.000 días en la Tierra",
            "200 Degrees",
            "Operación Palace (TV)",
            "28 días después",
            "28 días después",
            "7:35 de la mañana (C)",
            "9 extraños",
            "A ciegas",
            "A Roma con amor",
            "A Serbian Film",
            "Abducted in Plain Sight",
            "Acordes y desacuerdos",
            "Ad Astra",
            "Adiós Babilonia",
            "Adolfo Suárez, el presidente (Miniserie de TV)",
            "Aguirre, la cólera de Dios",
            "Alatriste",
            "Algo pasa con Mary",
            "Alguien voló sobre el nido del cuco",
            "Alien, el octavo pasajero",
            "Amadeus",
            "Amanda Knox",
            "Amanece, que no es poco",
            "Amarcord",
            "Amelie",
            "Amer",
            "American Beauty",
            "American History X",
            "American Psycho",
            "Ancha es Castilla / N'importe quoi (C)",
            "Andrei Rublev",
            "Ángeles y demonios",
            "Animales nocturnos",
            "Aniquilación",
            "Annie Hall",
            "Anticristo",
            "Ant-Man",
            "Area 407",
            "Argo",
            "Arma fatal",
            "Arrebato",
            "Asalto al tren Pelham 123",
            "Asesinato en el Orient Express",
            "Así en la Tierra como en el Infierno",
            "¡Átame!",
            "Aterrados",
            "Aterriza como puedas",
            "Atmósfera cero",
            "Atrapados en Chernóbil",
            "Atrápame si puedes",
            "Atún y chocolate",
            "Australia",
            "Avanti popolo",
            "Babadook",
            "Bananas",
            "Barry Lyndon",
            "Battle Royal High School",
            "Ben-Hur",
            "Beware the Slenderman",
            "Big Fish",
            "Billy Bathgate",
            "Blade Runner",
            "Blade Runner 2049",
            "Blow-Up (Deseo de una mañana de verano)",
            "Blue Jasmine",
            "Bone Tomahawk",
            "Braindead (Tu madre se ha comido a mi perro)",
            "Breathing Room",
            "Broadway Danny Rose",
            "Cadena perpetua",
            "Café Society",
            "Calibre",
            "Calle Cloverfield 10",
            "Cam",
            "Camino a la perdición",
            "Campeones",
            "Canciones del segundo piso",
            "Canino",
            "Carretera perdida",
            "Casa de arena y niebla",
            "Celda 211",
            "Celebración",
            "Cerdos salvajes (Con un par... de ruedas)",
            "Charlie y la fábrica de chocolate",
            "Cien años de perdón",
            "Ciudadano Kane",
            "Citizen X (Ciudadano X) (TV)",
            "The Clovehitch Killer",
            "El juego de la sospecha (Cluedo)",
            "Cobra Verde",
            "Coherence",
            "Colonia",
            "La comedia sexual de una noche de verano",
            "Cómo ser John Malkovich",
            "Con faldas y a lo loco",
            "Con la muerte en los talones",
            "Conocerás al hombre de tus sueños",
            "Contact",
            "Contagio",
            "Contratiempo",
            "Conversaciones con mi jardinero",
            "Crash (Colisión)",
            "Creep",
            "Crimen ferpecto",
            "Crisis en seis escenas (Miniserie de TV)",
            "Cromosoma 3",
            "Memories of Murder (Crónica de un asesino en serie)",
            "Cuatro bodas y un funeral",
            "Cube Zero",
            "Cuento de invierno",
            "Cuidado con los extraños",
            "Cyrano de Bergerac",
            "Dalí, maestro de sueños (TV)",
            "Un pueblo llamado Dante's Peak",
            "Danzad, danzad, malditos",
            "Dead Set: Muerte en directo (Miniserie de TV)",
            "Dear Zachary: A Letter to a Son About His Father",
            "Death Note",
            "Grindhouse (Death Proof)",
            "Déjate llevar",
            "Delicatessen",
            "Delitos y faltas",
            "Mi novia es un zombie",
            "Dentro del laberinto",
            "Desaparecidos sin rastro",
            "Desmontando a Harry",
            "Despedidas",
            "Después de tantos años",
            "Destino final 5",
            "Días de radio",
            "Dies irae",
            "Diez negritos",
            "Diez negritos",
            "Django desencadenado",
            "Dobbiamo parlare",
            "Dogville",
            "Dolor y gloria",
            "Donnie Darko",
            "Drácula, un muerto muy contento y feliz",
            "Dublineses (Los muertos)",
            "Dune",
            "Dunkerque",
            "Efectos secundarios",
            "El adversario",
            "El afinador de terremotos",
            "El americano impasible",
            "El amor es más fuerte que las bombas",
            "El ángel exterminador",
            "El árbol de los zuecos",
            "El bar",
            "El caballero oscuro",
            "El cabo del miedo",
            "El cadáver de Anna Fritz",
            "El caníbal japonés",
            "El capital humano",
            "El caso Alcàsser (Miniserie de TV)",
            "El caso Farewell",
            "El caso sk1",
            "The Human Centipede (First Sequence)",
            "El club de la lucha",
            "El cocinero, el ladrón, su mujer y su amante",
            "El código Da Vinci",
            "Sayat Nova (El color de la granada)",
            "El columpio",
            "El concierto",
            "El corredor del laberinto",
            "El corredor del laberinto: Las pruebas",
            "El cuchillo en el agua",
            "El cuerpo",
            "El desencanto",
            "El desierto rojo",
            "El día de la bestia",
            "El dictador",
            "El discurso del Rey",
            "El dormilón",
            "El eclipse",
            "El enigma de Gaspar Hauser",
            "El escritor",
            "El evangelio según San Mateo",
            "El examen (TV)",
            "El festín de Babette",
            "El final de todo",
            "El gatopardo",
            "El gran dictador",
            "El gran Lebowski",
            "El gran torneo",
            "El grito",
            "El Hobbit: La batalla de los cinco ejércitos",
            "El Hobbit: La desolación de Smaug",
            "El Hobbit: Un viaje inesperado",
            "El hombre de las mil caras",
            "El hombre de más",
            "El hombre elefante",
            "El hombre que conocía el infinito",
            "El honor de los Prizzi",
            "El hundimiento",
            "El ilusionista",
            "El infinito",
            "El inocente",
            "El investigador: La historia de un crimen británico (TV)",
            "El juego de Gerald",
            "El laberinto del fauno",
            "Adaptation (El ladrón de orquídeas)",
            "El luchador",
            "El manantial de la doncella",
            "El mensajero",
            "El método",
            "El milagro de P. Tinto",
            "El núcleo",
            "El número 23",
            "El orfanato",
            "El oro de Moscú",
            "El pacto",
            "El padrino. Parte II",
            "El pasajero",
            "El penalti más largo del mundo",
            "El príncipe de las tinieblas",
            "El proyecto de la bruja de Blair",
            "El proyecto Williamson (Miniserie de TV)",
            "El puente de los espías",
            "El rastro del mal (TV)",
            "El regalo",
            "El reportero",
            "El resplandor",
            "El rito",
            "El ritual",
            "El sabor de las cerezas",
            "El secdleto de la tlompeta (C)",
            "El secreto de los McCann",
            "El secreto de Marrowbone",
            "El secreto de sus ojos",
            "El sentido de la vida",
            "El sexto sentido",
            "El show de Truman (Una vida en directo)",
            "El solista",
            "El sueño de Casandra",
            "El tercer hombre",
            "El topo",
            "El tren de la bruja (C)",
            "El último disparo",
            "El último samurái",
            "El viaje de Chihiro",
            "El vicio del poder",
            "El vuelo del Fénix",
            "Elephant",
            "Eliminado",
            "En la boca del miedo",
            "En la cuerda floja",
            "En la mente del asesino",
            "En tierra hostil",
            "Encuentros paranormales",
            "Entrevista con el vampiro",
            "Eros",
            "Españistán (La burbuja inmobiliaria) (C)",
            "Europa One",
            "Europesadilla, Alguien se ha comido a la clase media (C)",
            "Evasión o victoria",
            "Horizonte Final",
            "Excalibur",
            "Excelentísimos cadáveres",
            "Expediente 39",
            "Eyes Wide Shut",
            "Family Man",
            "Fando y Lis",
            "Fargo",
            "Fata Morgana",
            "Feliz día de tu muerte",
            "Fitzcarraldo",
            "Florence Foster Jenkins",
            "Forrest Gump",
            "Frenético",
            "Fresas salvajes",
            "Furia de titanes",
            "Gamer",
            "Gattaca",
            "Ginger y Fred",
            "Giro inesperado",
            "Gladiator",
            "Gosford Park",
            "Gran Torino",
            "Granujas de medio pelo",
            "Gravity",
            "Green Room",
            "Gremlins",
            "Gritos y susurros",
            "Guerra Mundial Z",
            "Habitación en Roma",
            "Hable con ella",
            "Hamlet",
            "Hancock",
            "Hannah y sus hermanas",
            "Hannibal",
            "Hannibal: el origen del mal",
            "Harold y Maude",
            "Harry Dean Stanton: Partly Fiction",
            "Harry Potter y las reliquias de la muerte - Parte 1",
            "Harry Potter y el prisionero de Azkaban",
            "Harry Potter y el cáliz de fuego",
            "Harry Potter y la orden del Fénix",
            "Harry Potter y el misterio del príncipe",
            "Harry Potter y las reliquias de la muerte - Parte 1",
            "Hereditary",
            "Hierro 3",
            "High Life",
            "Hijo de Caín",
            "Holocausto caníbal",
            "Holy motors",
            "Hombres de honor",
            "Hostel",
            "Hostel 2",
            "Hostel 3: De vuelta al horror",
            "House on Haunted Hill",
            "Huida a medianoche",
            "Identidad",
            "Il divo",
            "Indiana Jones y el reino de la calavera de cristal",
            "Indiana Jones y el templo maldito",
            "Indiana Jones y la última cruzada",
            "En busca del arca perdida",
            "Infectados",
            "Inland Empire",
            "Inocentada sangrienta",
            "Insidious",
            "Insomnio",
            "Interiores",
            "Interstellar",
            "Invasión zombie",
            "Invictus",
            "IO",
            "Irrational Man",
            "Irreversible",
            "It",
            "It Follows",
            "It’s Not the Time of my Life",
            "Jackie Brown",
            "Jobs",
            "Jodorowsky's Dune",
            "Johnny English",
            "Johnny English Returns",
            "Johnny English: De nuevo en acción",
            "Jurassic World",
            "Kiki, el amor se hace",
            "Kill Bill: Volumen 1",
            "Killing Ground",
            "Koyaanisqatsi",
            "K-Pax. Un universo aparte",
            "La anguila",
            "La autopsia de Jane Doe",
            "La balada de Buster Scruggs",
            "La boda de mi novia",
            "La búsqueda 2: El diario secreto",
            "La cabaña en el bosque",
            "La caja Kovak",
            "La casa al final de la calle",
            "La casa de cera",
            "La casa de los 1000 cadáveres",
            "La Celestina",
            "La chaqueta metálica",
            "La ciudad de las mujeres",
            "La comunidad",
            "La cuarta fase",
            "La cura del bienestar",
            "La dama de hierro",
            "La danza de la realidad",
            "La doctrina del shock",
            "La dolce vita",
            "La escopeta nacional",
            "La extraña que hay en ti",
            "La gran comilona",
            "La gran belleza",
            "La guerra de las galaxias. Episodio I: La amenaza fantasma",
            "La guerra de las galaxias. Episodio II: El ataque de los clones",
            "La guerra de las galaxias. Episodio III: La venganza de los Sith",
            "La guerra de las galaxias. Episodio IV: Una nueva esperanza",
            "La guerra de las galaxias. Episodio V: El imperio contraataca",
            "La guerra de las galaxias. Episodio VI: El retorno del Jedi",
            "La habitación del pánico",
            "La herencia Valdemar",
            "La hoguera de las vanidades",
            "La hora de la araña",
            "La hora del lobo",
            "La huella",
            "La huérfana",
            "La infancia de Iván",
            "La invasión",
            "La invasión de los ultracuerpos",
            "La invitación",
            "La isla de los condenados",
            "La isla mínima",
            "La liga de los hombres extraordinarios",
            "La lista de Schindler",
            "La llave del mal",
            "La maldición del escorpión de jade",
            "La mansión de los horrores",
            "La máscara",
            "La matanza de Texas: El origen",
            "La mejor oferta",
            "La mirada de Antonioni (C)",
            "La momia",
            "El beso de la momia 2",
            "La momia: La tumba del emperador Dragón (La momia 3)",
            "La monja",
            "La montaña sagrada",
            "La muerte y la doncella",
            "La naranja mecánica",
            "La niebla",
            "La novia cadáver",
            "La partita lenta (C)",
            "La pasión de Juana de Arco",
            "La piel que habito",
            "Anarchy: La noche de las bestias",
            "La red social",
            "La ruta natural (C)",
            "La Sapienza",
            "La semilla del diablo",
            "La sombra de la sospecha",
            "La Strada",
            "La terminal",
            "La tierra de los muertos vivientes",
            "La trampa del mal",
            "La última noche de Boris Grushenko",
            "La Venus de las pieles",
            "La vida de Brian",
            "La vida de David Gale",
            "La vida en una canción",
            "La vida es bella",
            "La visita",
            "Las brujas de Zugarramurdi",
            "Las colinas tienen ojos",
            "Las consecuencias del amor",
            "Las mejores intenciones",
            "Las mil y una noches",
            "Las vacaciones de Mr. Bean (Mr. Bean 2)",
            "Las vidas posibles de Mr. Nobody",
            "Las vírgenes suicidas",
            "Lasa y Zabala",
            "El discreto encanto de la burguesía",
            "La cena de los idiotas",
            "Leaving Las Vegas",
            "Lejos de la tierra quemada",
            "Pequeña Miss Sunshine",
            "Litus",
            "Lo que la verdad esconde",
            "Lock & Stock",
            "Lolita",
            "Long Shot",
            "Los abrazos rotos",
            "Los amantes pasajeros",
            "Los caballeros de la mesa cuadrada y sus locos seguidores",
            "Los chicos del coro",
            "Los crímenes de Oxford",
            "Los cronocrímenes",
            "Los cuentos de Canterbury",
            "Los dos papas",
            "Los girasoles ciegos",
            "Los hombres que miraban fijamente a las cabras",
            "Los inútiles",
            "Los juegos del hambre",
            "Los odiosos ocho",
            "Los olvidados de Phoenix",
            "Los padres de ella",
            "Los pájaros",
            "Los santos inocentes",
            "Los sueños de Akira Kurosawa",
            "Los últimos días en Marte",
            "Lost in Translation",
            "Luna de hiel",
            "Macbeth",
            "Mad Max. Salvajes de autopista",
            "Madre!",
            "Mafia. ¡Estafa como puedas!",
            "Magia a la luz de la luna",
            "Magnolia",
            "Making a Murderer (Serie de TV)",
            "Malavita",
            "Malditos bastardos",
            "Malevolent",
            "Malos tiempos en El Royale",
            "Mandy",
            "Manhattan",
            "Manhunt: Unabomber (Miniserie de TV)",
            "Máquina de guerra",
            "Mar adentro",
            "Maridos y mujeres",
            "Mátalos suavemente",
            "Match Point",
            "Matrix",
            "Matrix Reloaded",
            "Me llaman Radio",
            "Medea",
            "Mejor... imposible",
            "Melanie. The Girl With All the Gifts",
            "Memento",
            "Mentes en blanco",
            "Mentiroso compulsivo",
            "Mi enemigo íntimo",
            "Mi gran boda griega",
            "Mi querida España (TV)",
            "Mickey ojos azules",
            "Medianoche en París",
            "Midsommar",
            "Mirindas asesinas (C)",
            "Misery",
            "Miss Violence",
            "Misterioso asesinato en Manhattan",
            "Moby Dick",
            "Monsieur Batignole",
            "Moon",
            "Mujeres al borde de un ataque de nervios",
            "Mulholland Drive",
            "Asesinato... 1-2-3",
            "Musarañas",
            "My Little Eye (La cámara secreta)",
            "Mystic River",
            "Napoleon Dynamite",
            "Asesinos natos",
            "La tienda",
            "Nido de cuervos",
            "Nine Dead",
            "Nivel 13",
            "No amarás",
            "No dejes de mirar",
            "No es país para viejos",
            "No habrá paz para los malvados",
            "No mires atrás",
            "No se lo digas a nadie",
            "Noche de lobos",
            "Nunca es demasiado tarde",
            "Ocean's 13 (Ocean's Thirteen)",
            "Ocean's Twelve",
            "Océanos de fuego (Hidalgo)",
            "Ocean's 8",
            "Ocho apellidos catalanes",
            "Ocho apellidos vascos",
            "Fellini, ocho y medio (8½)",
            "Ojos negros",
            "Oliver Twist",
            "Ordet (La palabra)",
            "Orgullo + Prejuicio + Zombies",
            "Origen",
            "Otra mujer",
            "Otto; or Up with Dead People",
            "Pacific Rim",
            "Pandorum",
            "Parásitos",
            "Patton",
            "Perfetti sconosciuti",
            "Persona",
            "Pesadilla en Elm Street",
            "Philadelphia",
            "Pi, fe en el caos",
            "Pitch Black",
            "Plan de escape",
            "Plan oculto",
            "Poderosa Afrodita",
            "Pollock: La vida de un creador",
            "Poseidón",
            "Premonición",
            "Primos",
            "Prince of Persia: Las arenas del tiempo",
            "Psicosis",
            "Puertas abiertas",
            "Pulp Fiction",
            "Pura formalidad",
            "Que Dios nos perdone",
            "Quemar después de leer",
            "Ran",
            "Ratatouille",
            "Réalité",
            "[•REC]²",
            "Recuerdos",
            "Red State",
            "Redención (Los casos del Departamento Q)",
            "Relatos salvajes",
            "Religulous",
            "Repulsión",
            "Reservoir Dogs",
            "Retratos de soledad",
            "Revolutionary Road",
            "Rey de reyes",
            "RocknRolla",
            "Rumbo a la muerte",
            "Salir del armario",
            "Saló, o los 120 días de Sodoma",
            "Salvar al soldado Ryan",
            "Satyricon",
            "Saw II",
            "Saw III",
            "Saw IV",
            "Saw V",
            "Saw VI",
            "Saw VII 3D",
            "Scary Movie 2",
            "Scary Movie 3",
            "Escenas en una galería",
            "Scoop",
            "Scorned",
            "Scream 2",
            "Se montó la gorda",
            "Secuestrados",
            "Secuestro",
            "Senderos de gloria",
            "Señales del futuro",
            "Serenity",
            "Seven",
            "Sexo fácil, películas tristes",
            "Shutter Island",
            "Si la cosa funciona",
            "Siete psicópatas",
            "Simiocracia (Crónica de la gran resaca económica) (C)",
            "Simón del desierto",
            "Sin perdón",
            "Sin salida",
            "Sinister",
            "Slither: La plaga",
            "Slumdog Millionaire",
            "Snatch. Cerdos y diamantes",
            "Snowden",
            "Solaris",
            "Solo en casa 2: Perdido en Nueva York",
            "Solo en casa 3",
            "Solo en casa 4 (TV)",
            "Sombras y niebla",
            "Somos los Miller",
            "Sospechosos habituales",
            "Código Fuente",
            "Spacewalker",
            "Los conspiradores del placer",
            "Spoon Wars (C)",
            "Star Trek",
            "Stigmata",
            "Stockholm",
            "Sueños de un seductor",
            "Symbol",
            "Tarde para la ira",
            "Tau",
            "Taxi Driver",
            "Te doy mis ojos",
            "¿Teléfono rojo? Volamos hacia Moscú",
            "Tengo algo que deciros",
            "Hidden: Terror en Kingsville",
            "Tesis",
            "Tesis",
            "Testigo de cargo",
            "The Amputee (C)",
            "The Belko Experiment",
            "The Body",
            "The Booth (Serie de TV)",
            "The Crazies",
            "The Discovery",
            "El miedo al 13",
            "The Four Year Plan",
            "Full Monty",
            "The Game",
            "Los goonies",
            "The Hole",
            "La casa es negra (C)",
            "Los juegos del resacón",
            "The Iceman Tapes: Conversations with a Killer (TV)",
            "The Jinx (El gafe) (Miniserie de TV)",
            "The Killing Room",
            "Los inquilinos (The Lodgers)",
            "The Man from Earth",
            "The Onion Movie",
            "Los Pelayos",
            "The Rocky Horror Picture Show",
            "Una historia verdadera",
            "The Young Pope (Serie de TV)",
            "Un lugar donde quedarse",
            "Tiburón",
            "Las Hurdes (Tierra sin pan)",
            "Tirad sobre el pianista",
            "Titanic",
            "Todo es de color",
            "Todo sobre mi madre",
            "Toma el dinero y corre",
            "Tomates verdes fritos",
            "Torrente 2: Misión en Marbella",
            "Torrente 3: El protector",
            "Torrente 4: Lethal Crisis (Crisis Letal)",
            "Torrente 5: Operación Eurovegas",
            "Transsiberian",
            "Tristana",
            "Troya",
            "Tú eres el siguiente",
            "Tumba abierta",
            "Twin Peaks: Fuego camina conmigo",
            "Última llamada",
            "Un cadáver a los postres",
            "Un día de furia",
            "Un dios salvaje",
            "Un final made in Hollywood",
            "Un funeral de muerte",
            "Un lugar tranquilo",
            "Un perro andaluz (C)",
            "Un plan brillante",
            "Una paloma se posó en una rama a reflexionar sobre la existencia",
            "Under the Skin",
            "Uno de los nuestros",
            "V de Vendetta",
            "Valkiria",
            "Van Helsing",
            "Velvet Buzzsaw",
            "Verdad o reto",
            "Verónica",
            "Viaje al centro de la Tierra",
            "Villaviciosa de al lado",
            "Viridiana",
            "Viva la libertad",
            "Viva la muerte",
            "Volver",
            "Willow",
            "Would You Rather",
            "Zabriskie Point",
            "Zelig",
            "Zodiac",
            "Zohan: Licencia para peinar",
            "Zombies party",
            "¿Qué tal, Pussycat? (¿Qué tal, gatita?)",
            "¿Y tú quién eres?",
            "Doce hombres sin piedad",
            "1997: Rescate en Nueva York",
            "2001: Una odisea del espacio",
            "A 47 metros",
            "Ahora me ves...",
            "Apocalypse Now",
            "Arsène Lupin",
            "Asesinato en el Orient Express",
            "Atómica (Atomic Blonde)",
            "Austin Powers: Misterioso agente internacional",
            "Bajo cero",
            "Black Mirror: Bandersnatch",
            "Bitelchús",
            "Bikini: Una historia real (C)",
            "Blancanieves y los siete enanitos",
            "Volar por los aires",
            "Terciopelo azul",
            "Boccaccio '70",
            "Borat: Lecciones culturales de América para beneficio de la gloriosa nación de Kazajistán",
            "Bukowski: Born into This",
            "Buried (Enterrado)",
            "Cabin Fever",
            "Caché (Escondido)",
            "Cargo",
            "Casino",
            "Mindhunters",
            "Chernobyl (Miniserie de TV)",
            "El círculo",
            "Cómo sobrevivir a una despedida",
            "Crash (Colisión)",
            "4 meses, 3 semanas, 2 días",
            "Cube 2: Hypercube",
            "Lugares oscuros",
            "Deadly Virtues: Love. Honour. Obey",
            "Disonancia (C)",
            "Doce hombres sin piedad (TV)",
            "No respires",
            "Drácula de Bram Stoker",
            "Eat",
            "Amanecer de los muertos",
            "El apóstol",
            "The Human Centipede 2 (Full Sequence)",
            "El conde de Montecristo (Miniserie de TV)",
            "El día más largo",
            "El dragón rojo",
            "L'éden et après",
            "El ejército de las tinieblas",
            "El espejo",
            "El golpe",
            "El juego de la muerte (TV)",
            "Lago Shimmer",
            "Los expedientes antiguos X (Serie de TV)",
            "Náufrago",
            "El padrino",
            "El jovencito Frankenstein",
            "American Crime Story: The People v. O.J. Simpson (Miniserie de TV)",
            "El Reino",
            "El señor de los anillos: El retorno del rey",
            "Sacrificio",
            "Shooter: El tirador",
            "El unicornio",
            "Æon Flux",
            "Escalofrío",
            "Juerga hasta el fin",
            "¡Olvídate de mí!",
            "Posesión infernal",
            "Exitus interruptus - Der Tod ist erst der Anfang",
            "Fallen",
            "Fahrenheit 9/11",
            "Roma",
            "Enganchados a la muerte",
            "Funny Games",
            "Funny Games",
            "Noche de juegos",
            "Juego de tronos (Serie de TV)",
            "Déjame salir",
            "Glass (Cristal)",
            "Adiós pequeña, adiós",
            "Perdida",
            "Atrapado en el tiempo",
            "Habitación sin salida (Vacancy)",
            "Los abandonados",
            "Happy Birthday Mr. Zombie (C)",
            "Harry Potter y la cámara secreta",
            "Hitman",
            "Un hombre lobo americano en Londres",
            "Cómo acabar con tu jefe",
            "Howl (Aullido)",
            "Hush (Silencio)",
            "Escupiré sobre tu tumba (Dulce venganza)",
            "Instinto",
            "It",
            "John Q.",
            "Kill Bill: Volumen 2",
            "Kingsman: Servicio secreto",
            "Toc Toc",
            "Kung Fu Sion",
            "La aventura",
            "La búsqueda",
            "La cabina (TV)",
            "La carretera (The Road)",
            "La colmena",
            "El señor de los anillos: La comunidad del anillo",
            "La cosa (El enigma de otro mundo)",
            "La cosa (The Thing)",
            "El guateque",
            "La guerra de los mundos",
            "La historia de siempre (C)",
            "La isla de las flores (C)",
            "El muelle (La Jetée)",
            "La jungla de cristal",
            "El hombre de la máscara de hierro",
            "La matanza de Texas",
            "La matanza de Texas",
            "La niebla",
            "Noche de fin de año",
            "La noche",
            "The Cloverfield Paradox",
            "The Purge: La noche de las bestias",
            "Election: La noche de las bestias",
            "La rosa púrpura de El Cairo",
            "La señal",
            "La herencia Valdemar II: La sombra prohibida",
            "El señor de los anillos: Las dos torres",
            "Le Quattro Volte",
            "Los desenterrados de Le Tréport (Serie de TV)",
            "Life (Vida)",
            "Llega de noche",
            "Los chicos del maíz",
            "El secreto de los hermanos Grimm",
            "Los padres de él",
            "Los siete samuráis",
            "Más allá de la duda",
            "Más allá de las nubes",
            "Million Dollar Baby",
            "Moisés (TV)",
            "La gran aventura de Mortadelo y Filemón",
            "Mortadelo y Filemón. Misión: salvar la Tierra",
            "Dos rubias de pelo en pecho",
            "Nanuk, el esquimal",
            "Next",
            "Noche y día",
            "Nosferatu, vampiro de la noche",
            "Nymphomaniac. Volumen 1",
            "Nymphomaniac. Volumen 2",
            "Objectified",
            "Ocean's Eleven (Hagan Juego)",
            "8½ mujeres",
            "Oldboy",
            "Old Boy",
            "Érase una vez en... Hollywood",
            "Paris, Texas",
            "Pasolini",
            "Perdidos (Lost) (Serie de TV)",
            "Grindhouse (Planet Terror)",
            "Primer",
            "Prison Break (Serie de TV)",
            "Prisioneros",
            "Cuarentena",
            "Un italiano en Noruega",
            "Conejos (Rabbits) (Miniserie de TV)",
            "Rape Zombie: La lujuria de los muertos vivientes",
            "[•REC]",
            "[•REC]³: Génesis",
            "Revenge",
            "Rose Red (Miniserie de TV)",
            "Saraband (TV)",
            "Saw",
            "Escape Room",
            "El precio del poder",
            "Scary Movie",
            "Schlaf (Sleep) (C)",
            "Scream. Vigila quién llama",
            "She's Lost Control (C)",
            "Sin City (Ciudad del pecado)",
            "Solo en casa",
            "Múltiple",
            "Stalker",
            "Stargate, puerta a las estrellas",
            "Starsky & Hutch: La película",
            "Perros de paja",
            "Escuadrón suicida",
            "Summer Camp",
            "Sunshine",
            "Sweet Home",
            "Tchang (C)",
            "The Box",
            "The Boy",
            "El canal",
            "The Code",
            "The Collector",
            "Cube",
            "The Den",
            "Infiltrados",
            "Descenso",
            "El infinito",
            "El experimento",
            "El regalo",
            "La abuela (The Grandmother)",
            "The Guilty",
            "The Holiday (Vacaciones)",
            "The Horribly Slow Murderer with the Extremely Inefficient Weapon (C)",
            "Ladykillers",
            "Life Aquatic",
            "Marte (The Martian)",
            "Bolsa de cadáveres (TV)",
            "The Night Of (Miniserie de TV)",
            "La víctima perfecta",
            "The Report",
            "White Chamber",
            "Wicker Man",
            "Todo lo que siempre quiso saber sobre el sexo y nunca se atrevió a preguntar",
            "Tora! Tora! Tora!",
            "Torrente, el brazo tonto de la ley",
            "Tren a Busan",
            "Transcendence",
            "Aguaespejo granadino (C)",
            "Tres colores: Azul",
            "Tropic Thunder, ¡una guerra muy perra!",
            "Twin Peaks (Serie de TV)",
            "The Score (Un golpe maestro)",
            "El soplo al corazón",
            "Una serie de catastróficas desdichas de Lemony Snicket",
            "Nosotros",
            "Vampyr, la bruja vampiro",
            "Veronica Mars",
            "Videodrome",
            "Weekend",
            "What's Virgin Mean? (C)",
            "Corazón salvaje",
            "Wild Wild Country (Miniserie de TV)",
            "Winchester: La casa que construyeron los espíritus",
            "Yo, Claudio (Miniserie de TV)",
            "La juventud",
            "Z.",
            "Bienvenidos a Zombieland",
            "Zombis nazis",
            "Zombis nazis 2"



            );

}
